language: node_js
node_js:
  - "0.10"

install:
  - "bash scripts/install.sh -ipn"

before_script:
  - "source ~/.bashrc"
  - "npm install"
  - "cd node-datasource"
  - "npm start &"
  - "sleep 10"
  - "cd .."

script:
  - "ls /home/travis/build/noahprince22/xcore/test/lib"
  - "cat /home/travis/build/noahprince22/xcore/test/lib/login_data.js"
  - "npm run-script test-build"
