language: node_js
node_js:
  - "0.10"

install:
  - "bash scripts/install.sh -ipn"

before_script:
  - "source ~/.bashrc"
  - "npm install -g mocha"
  - "cd node-datasource"
  - "npm start &"
  - "sleep 10"
  - "cd .."

script:
  - "npm run-script test-build"
